import type { Persona } from './types.js';

export const PERSONAS: Persona[] = [
  { personaId: 'north-delhi-brand-strategist', name: 'Aditi Mehra', age: 29, city: 'New Delhi', state: 'Delhi', region: 'North India', occupation: 'Brand strategist', description: 'Urban, culturally curious premium shopper with experience in consumer and lifestyle brands.', evaluationLens: 'Brand point of view, cultural nuance, premium coherence, and commercial brand trust.' },
  { personaId: 'north-jaipur-working-parent', name: 'Raghav Sharma', age: 38, city: 'Jaipur', state: 'Rajasthan', region: 'North India', occupation: 'Operations manager and working parent', description: 'Practical household shopper balancing family occasions, durability, and value.', evaluationLens: 'Wearability, occasion fit, clarity, durability cues, and shared household confidence.' },
  { personaId: 'south-bengaluru-product-designer', name: 'Nandini Rao', age: 31, city: 'Bengaluru', state: 'Karnataka', region: 'South India', occupation: 'Product designer', description: 'Design-conscious digital professional with a preference for coherent, contemporary systems.', evaluationLens: 'Visual system, product legibility, restraint, and usability.' },
  { personaId: 'south-kochi-finance-professional', name: 'Arjun Mathew', age: 35, city: 'Kochi', state: 'Kerala', region: 'South India', occupation: 'Finance professional', description: 'Selective practical premium shopper who checks comfort, climate, construction, and trust.', evaluationLens: 'Climate suitability, comfort, material believability, sizing, and practical value.' },
  { personaId: 'south-chennai-student-creator', name: 'Meera Krishnan', age: 22, city: 'Chennai', state: 'Tamil Nadu', region: 'South India', occupation: 'University student and content creator', description: 'Mobile-first, budget-aware young shopper who discovers fashion through social content.', evaluationLens: 'Youth relevance, relatability, beauty realism, digital appeal, and versatility.' },
  { personaId: 'west-mumbai-entrepreneur', name: 'Sana Merchant', age: 34, city: 'Mumbai', state: 'Maharashtra', region: 'West India', occupation: 'Consumer-brand entrepreneur', description: 'Highly experienced premium e-commerce shopper with a brand-owner perspective.', evaluationLens: 'Conversion, differentiation, target-customer fit, merchandising, and price justification.' },
  { personaId: 'west-ahmedabad-textile-professional', name: 'Devika Shah', age: 42, city: 'Ahmedabad', state: 'Gujarat', region: 'West India', occupation: 'Textile sourcing professional', description: 'Craft and product-development specialist attentive to fabric behavior and finishing.', evaluationLens: 'Construction, textile behavior, finishing, craft integrity, and material credibility.' },
  { personaId: 'east-kolkata-creative-professional', name: 'Ishita Sen', age: 30, city: 'Kolkata', state: 'West Bengal', region: 'East India', occupation: 'Art director and visual storyteller', description: 'Editorial creative professional interested in cultural observation and visual authorship.', evaluationLens: 'Storytelling, regional nuance, emotional credibility, restraint, and cultural specificity.' },
  { personaId: 'east-bhubaneswar-public-sector-professional', name: 'Pranav Das', age: 40, city: 'Bhubaneswar', state: 'Odisha', region: 'East India', occupation: 'Public-sector programme manager', description: 'Cautious established-platform shopper seeking trust, clarity, comfort, and broad relevance.', evaluationLens: 'Broad-market trust, clarity, appropriateness, value, and relevance beyond metros.' },
  { personaId: 'northeast-guwahati-consultant', name: 'Tashi Deka', age: 28, city: 'Guwahati', state: 'Assam', region: 'Northeast India', occupation: 'Management consultant', description: 'Digitally connected professional attentive to plural representation and access realities.', evaluationLens: 'Visibility, anti-exoticization, regional pluralism, fit, delivery, and inclusive premium design.' },
];

if (PERSONAS.length !== 10 || new Set(PERSONAS.map((persona) => persona.personaId)).size !== 10) {
  throw new Error('Exactly ten unique personas are required.');
}
